services:
# Web Server (Proxy)
  nginx: 
    build: ./services/nginx
    image: nginx
    container_name: nginx 
    ports:
      - "443:443"
    volumes:
      - ./services/nginx/conf:/etc/nginx/conf.d 
      - ./certs:/etc/ssl/certs
      - ./private:/etc/ssl/private
    networks:
      - transcendence
    depends_on:
      mariadb:
        condition: service_healthy
      frontend:
        condition: service_healthy
    restart: always

# Frontend (React)
  frontend:
    build: ./services/frontend
    image: frontend
    container_name: frontend
    volumes:
      - ./services/frontend/app:/app
      - node_modules_vm:/app/node_modules # To keep the container internal modules
    networks:
      - transcendence
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5173/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: always

  adminer:
    build: ./services/adminer
    image: adminer
    container_name: adminer
    networks:
      - transcendence
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always

  # Database
  mariadb:
    build: ./services/mariadb
    image: mariadb
    container_name: mariadb
    environment:
      MARIADB_DATABASE: ${NAME_DB}
      MARIADB_USER: ${USER_NAME_DB}
      MARIADB_PASSWORD: ${USER_PASSWD_DB}
      MARIADB_ROOT_PASSWORD: ${ROOT_PASSWD_DB}
    volumes:
      - mariadb_vm:/var/lib/mysql
    networks:
      - transcendence
    healthcheck:
      test: ["CMD-SHELL", "test -s /var/lib/mysql/${NAME_DB} && mysqladmin ping -u root -p${ROOT_PASSWD_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    env_file: .env
    restart: always

volumes:
  node_modules_vm:

  mariadb_vm:
    driver: local
    driver_opts:
      device: "${PWD}/database"
      o: bind
      type: none

networks:
  transcendence:
    name: transcendence
    driver: bridge


#Volumes and bind mounts that have to be remove when develompent ends:
#   - ./services/nginx/conf:/etc/nginx/conf.d
#   - ./services/frontend/app:/app
#   - node_modules_vm:/app/node_modules 
#   - ./services/nginx/conf:/etc/nginx/conf.d 